# Generated by Django 3.2.3 on 2021-06-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210609_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_day',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='user',
            name='movie_preference',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Preferencia de peliculas'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='user',
            name='run',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Run'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Alias'),
        ),
    ]
