# Generated by Django 3.2.4 on 2021-07-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210704_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='plot',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
